from .Tutu import NODE_CLASS_MAPPINGS as TUTU_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TUTU_DISPLAY_MAPPINGS, WEB_DIRECTORY
from .TutuPromptMaster import NODE_CLASS_MAPPINGS as PROMPT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PROMPT_DISPLAY_MAPPINGS

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {**TUTU_MAPPINGS, **PROMPT_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**TUTU_DISPLAY_MAPPINGS, **PROMPT_DISPLAY_MAPPINGS}

# AI nodes only - removed AiHelper and UI components
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']

